# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4, unique=True)),
                ('status', models.CharField(choices=[('NOT_ISSUED', 'NOT_ISSUED'), ('ISSUED', 'ISSUED'), ('REPAID', 'REPAID')], default='NOT_ISSUED', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Key')),
            ],
        ),
    ]
