# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 12:27
from __future__ import unicode_literals

import random
import string

from django.db import migrations

KEY_LENGTH = 4


def generate_keys(apps, schema_editor):
    for i in xrange(1000):
        chars = string.letters + string.digits
        Key = apps.get_model("api", "Key")
        Key.objects.create(value=''.join((random.choice(chars)) for x in range(KEY_LENGTH)))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_keys),
    ]
